all:
  children:
    masters:
      hosts:
        k8s-master01:
          ansible_host: 10.0.0.28
          k8s_zone: proxmox-node0
        k8s-master02:
          ansible_host: 10.0.0.29
          k8s_zone: proxmox-node0
        k8s-master03:
          ansible_host: 10.0.0.30
          k8s_zone: proxmox-node1

    workers:
      hosts:
        k8s-worker01:
          ansible_host: 10.0.0.31
          k8s_zone: proxmox-node0
        k8s-worker02:
          ansible_host: 10.0.0.32
          k8s_zone: proxmox-node0
        k8s-worker03:
          ansible_host: 10.0.0.33
          k8s_zone: proxmox-node1
        k8s-worker04:
          ansible_host: 10.0.0.34
          k8s_zone: proxmox-node1